name: Bug report
description: Create a report to help us improve
title: "[BUG] "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: input
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem

  - type: input
    id: desktop-info
    attributes:
      label: Desktop (please complete the following information)
      description: |
        - OS: [e.g. macOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]

  - type: input
    id: smartphone-info
    attributes:
      label: Smartphone (please complete the following information)
      description: |
        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS8.1]
        - Browser [e.g. stock browser, safari]
        - Version [e.g. 22]

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here