name: Custom issue
description: Describe this issue template's purpose here.
title: "[CUSTOM] "
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Describe the issue**
        A clear and concise description of what the issue is.

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: input
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here