name: Test issue
description: Use this template for creating test-related issues
title: "[TEST] "
labels: [test]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Describe the test issue**
        A clear and concise description of what the test issue is.

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: input
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the test issue here